### ISSUE TITLE
如果使用Page来展现我觉得会更好

### ISSUE THREAD

**Issue by AnYuan** [mengxiangyue/The-Swift-2.0-Programming-Language-playground#1]
希望可以采用page形式展现

**Comment by bapuqln** [comment]
这个是最好的形式，你觉得那里感兴趣，可以直接写代码测试了。

**Comment by mengxiangyue** [comment]
@AnYuan @bapuqln  Playground支持md之后，这种形式比较好

**Comment by AnYuan** [comment]
我说的是playground 的page，这样一个playground就可以，还可以page之间链接上。当然只是个建议，哈哈。
